server:
  servlet:
    context-path:   #current service name context path

spring:
  application.name:   #current service name to be used by the eureka server 

  
      
#Health Actuator Config
management: 
  endpoints.web.exposure.include: health,env,refresh
  endpoint.health.show-details: always
  endpoints.web.base-path: /
  endpoint.env.enabled: true  
  endpoint.refresh.enabled: true

eureka:         #tells about the Eureka server details and its refresh time.
  instance:
    initial-status: starting
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://internal-ac8c115af554946d781b9057ef15252d-1817341529.us-east-1.elb.amazonaws.com/midnight-service-registry/eureka}
    healthcheck:
      enabled: true
    lease:
      duration: 5
